### ISSUE TITLE
openqa failed to work with .raw.xz images

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi-functional-tests#4]
For still unknown reasons the .raw.xz images from the integration tests do not work when used in a job for openqa. Interesting enough the .qcow2 and also vmdk.xz images works which leads to the assumption it could be a problem in openqa itself.

Dan suggested to get in contact with Oliver to clarify on that end

**Comment by schaefi** [comment]
I've tested the .raw.xz images built in the integration test projects and the simply boot with e.g

```
kvm kiwi-test-image-disk.x86_64-1.42.1-Build6.3.raw -serial stdio
```

**Comment by dcermak** [comment]
@okurz @foursixnine Can you help us out here? I've tried to feed openQA the compressed raw disk image as `HDD_1_DECOMPRESS_URL` and openQA appears to do "the right thing" with respect to fetching and decompressing the image, but it just fails to boot from it (it does not find any boot device).

**Comment by okurz** [comment]
I am happy to have a look. Would you happen to have an openQA job run that shows the problem?

**Comment by dcermak** [comment]
I believe that this was caused by me being dumb, because the issue eventually disappeared after I changed some variables around.
