### ISSUE TITLE
how to handle EFI/UEFI boot process in openqa

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi-functional-tests#5]
For testing we require that the qemu VM is called in EFI/UEFI mode. From a qemu perspective this means:

```
qemu-kvm -bios /usr/share/qemu/ovmf-x86_64-ms.bin ...
```

How can we setup the use of a custom firmware when running in openqa ?

**Comment by dcermak** [comment]
Judging from https://github.com/os-autoinst/os-autoinst/blob/master/doc/backend_vars.asciidoc it should boil down to setting the following variables:
- `UEFI`: 1
- `UEFI_PFLASH_CODE`: probably distribution specific, but on opensuse `/usr/share/qemu/ovmf-x86_64-ms-code.bin` is used
- `UEFI_PFLASH_VARS`: same as `_CODE`, only `/usr/share/qemu/ovmf-x86_64-ms-vars.bin` is used on opensuse instead

**Comment by dcermak** [comment]
The variables from https://github.com/OSInside/kiwi-functional-tests/issues/5#issuecomment-724780913 are sufficient to make openqa boot in UEFI mode. The monstrosity, ehm, I mean "test suite" that I'm developing in #3 is utilizing these.

**Comment by dcermak** [comment]
Fixed via #10.
