### ISSUE TITLE
Failing images

### ISSUE THREAD

**Issue by dcermak** [OSInside/kiwi-functional-tests#8]
I am getting closer to *finally* getting #3 into decent shape, but there's still a ton of failures. For some of these I am not sure whether these are caused by the image being broken or openQA not launching it properly or something else.

### Tumbleweed
- [x] https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/tumbleweed/images/iso/kiwi-test-image-disk-ramdisk.x86_64-1.42.1-Build9.26.install.iso fails to create a bootable disk image

- [x] https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-orthos: `raw.xz` disk image does not display anything in UEFI mode
- [x] https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-overlayroot: broken, should be fixed by https://github.com/OSInside/kiwi/pull/1864
- [x] https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-qcow-openstack: does not launch in UEFI mode
- [x] https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-disk-legacy, https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-disk-ramdisk and https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-custom-partitions do not install properly when booted from the `.install.iso`: they just reboot again and again until openQA kills the tests. This happens also in a VM created by virt-manager and both in UEFI and non UEFI mode.
- [x] https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-MicroOS: this is a weird one. When using the installation iso in UEFI mode, then the resulting disk image will display the installation on the second reboot as well! But this does not happen in non UEFI mode… See for the video recording: https://user-images.githubusercontent.com/45594031/123279000-bf8b5900-d507-11eb-8c7b-294f45f7d611.mp4

### Leap
- [x] https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/leap/images/iso/kiwi-test-image-disk-ramdisk.x86_64-1.15.3-Build9.7.install.iso fails to create a bootable disk image
- [x] https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:leap/test-image-disk-ramdisk: `.install.iso` hangs in UEFI and non UEFI mode

### Fedora 33
- [x] https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-microdnf: displays a non fatal grub error in UEFI and non-UEFI mode: 
![image](https://user-images.githubusercontent.com/45594031/123279773-7556a780-d508-11eb-8976-fc383c1c6f99.png)

**Comment by schaefi** [comment]
Hi @dcermak. Thanks much for your effort on the functional testing and sorry for my slow response.

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-orthos:
 
   If you look at the image description you see ```firmware="efi"```. This is an intentional setting for this image to run on EFI
   but no secure boot enabled. Not booting in secure boot mode for this image is therefore the expected result. Please note
   we have some image descriptions that are build with efi instead of uefi to also test the custom efi grub binary setup in kiwi.
   In the functional tests we should be aware of it and not treat it as an error unless the image is expected to boot in secure
   boot mode

* Add missing util-linux-systemd dependency to dracut-kiwi-overlay kiwi#1864

  Done now. I have submitted 9.23.40 to Staging and this will be used for the integration test builds now.

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-qcow-openstack:

  Correct and also intentional. If you look at the description it does not set any firmware and that defaults to BIOS. We
  intentionally want to build this image with legacy CSM capabilities only

**Comment by schaefi** [comment]
I'll test on the others in a minute. Give me some time to work this out

**Comment by schaefi** [comment]
* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-disk-ramdisk and https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-custom-partitions

I assume this to be related to the missing util-linux-systemd dependency #1864 without lsblk none of kiwi's dracut code will work properly

**Comment by schaefi** [comment]
* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-disk-legacy

  The custom oemboot kiwi description has not applied the util-linux-systemd dependency. I'm going to fix this now

**Comment by schaefi** [comment]
* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-MicroOS:

  I cannot reproduce this. It works just fine for me with the following test:

  ```
  $ qemu img create mydisk 40g
  $ kvm -cdrom kiwi-test-image-MicroOS.x86_64-16.0.0-Build9.23.install.iso -hda mydisk
     ==> reboot
  ```

  As long as the precedence for boot devices is on the disk it does not re-enter the install path.

  I think you are hitting an openQA issue in this regard

**Comment by schaefi** [comment]
* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-microdnf:
  
  Regarding grubenv and grub I can't do much here as I'm using the grub and the modules as they are pulled from Fedora.
  I don't expect this issue to be harmful and would ignore it. Thoughts ?

**Comment by schaefi** [comment]
* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:leap/test-image-disk-ramdisk:
 
  Worked for me if I give the VM enough memory. At least ```-m 8192```. But will retest tomorrow again

**Comment by Conan-Kudo** [comment]
> * https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-microdnf:
>   Regarding grubenv and grub I can't do much here as I'm using the grub and the modules as they are pulled from Fedora.
>   I don't expect this issue to be harmful and would ignore it. Thoughts ?

The error looks like we're not creating a file it expects to exist...

**Comment by Conan-Kudo** [comment]
Perhaps @martinezjavier might know what's going on here with the Fedora image?

**Comment by martinezjavier** [comment]
> Perhaps @martinezjavier might know what's going on here with the Fedora image?

On Fedora that `grubenv` file is created by Anaconda AFAIK.

**Comment by dcermak** [comment]
>     * https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:leap/test-image-disk-ramdisk:
>       Worked for me if I give the VM enough memory. At least `-m 8192`. But will retest tomorrow again

Indeed, increasing the amount of RAM for the VM to 4096 is enough and fixes this issue.

**Comment by dcermak** [comment]
Marcus Schäfer ***@***.***> writes:

> Hi @dcermak. Thanks much for your effort on the functional testing and sorry for my slow response.
>
> * https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-orthos:
>  
>    If you look at the image description you see ```firmware="efi"```. This is an intentional setting for this image to run on EFI
>    but no secure boot enabled. Not booting in secure boot mode for this image is therefore the expected result. Please note
>    we have some image descriptions that are build with efi instead of uefi to also test the custom efi grub binary setup in kiwi.
>    In the functional tests we should be aware of it and not treat it as an error unless the image is expected to boot in secure
>    boot mode

I am not using the secure boot UEFI payload for this image, just the
ordinary OVMF UEFI binary.

>
> * Add missing util-linux-systemd dependency to dracut-kiwi-overlay kiwi#1864
>
>   Done now. I have submitted 9.23.40 to Staging and this will be used for the integration test builds now.

Is that change included in the rebuild from yesterday?

> * https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-qcow-openstack:
>
>   Correct and also intentional. If you look at the description it does not set any firmware and that defaults to BIOS. We
>   intentionally want to build this image with legacy CSM capabilities only
>

I have turned off the run with UEFI=1 for the openstack image.

**Comment by dcermak** [comment]
Javier Martinez Canillas ***@***.***> writes:

>> Perhaps @martinezjavier might know what's going on here with the Fedora image?
>
> On Fedora that `grubenv` file is created by Anaconda AFAIK.

Maybe, but it is also available via rpms:
```
$ rpm -q --whatprovides /boot/grub2/grubenv
grub2-efi-ia32-2.06-2.fc34.x86_64
grub2-efi-x64-2.06-2.fc34.x86_64
```
(on f34)

**Comment by dcermak** [comment]
I have rerun the full openQA test suite on my local instance for Tumbleweed just now and still get the following failures:

- kiwi-test-image-orthos.x86_64-1.13.1-Build9.24.raw fails with `UEFI=1` and using the OVMF UEFI binaries **without** secure boot.
- kiwi-test-image-disk-ramdisk.x86_64-1.42.1-Build9.24.install.iso does not launch properly with and without UEFI even with 8192 MB of RAM. I guess that something else is broken here.
- kiwi-test-image-custom-partitions.x86_64-1.15.1-Build9.24.install.iso, kiwi-test-image-disk-legacy.x86_64-1.42.1-Build11.2.install.iso and kiwi-test-image-disk.x86_64-1.42.1-Build9.24.install.iso all do not launch with and without UEFI mode
- the created microos disk image still tries to install twice, but I have not looked into that yet so this might be an openQA/my test setup issue

**Comment by schaefi** [comment]
* kiwi-test-image-orthos.x86_64-1.13.1-Build9.24.raw fails with UEFI=1 and using the OVMF UEFI binaries without secure boot.

  I found the issue in the description for this one and fixed it. Should be solved after rebuild

**Comment by schaefi** [comment]
All the rest of your tests are still broken because

```
Press Enter for maintenance
(or press Control-D to continue): 
sh-5.1# 
sh-5.1# 
sh-5.1# lsblk 
sh: lsblk: command not found
sh-5.1# 
sh-5.1# 
sh-5.1# 

```

as long as this is not fixed it will not work.

Why the hell are we moving core stuff around :(

**Comment by schaefi** [comment]
I don't see the tests to pull in util-linux-systemd, that explains why nothing has changed... I just don't understand why

**Comment by schaefi** [comment]
[  286s] [ DEBUG   ]: 19:51:36 | system: (144/146) Installing: dracut-kiwi-lib-9.23.40-1.1.x86_64 [.......done

this is the latest one which should have Requires:       util-linux-systemd

but 

osc buildlog images x86_64 | grep util-linux-systemd

"no matches"

??

**Comment by schaefi** [comment]
```
# lsblk is part of util-linux-systemd on openSUSE
%if 0%{?suse_version}
Requires:       util-linux-systemd
%endif
```

is this working for TW ?

**Comment by schaefi** [comment]
This seemed to have no effect

```
rpm -qp --requires dracut-kiwi-lib-9.23.40-1.1.x86_64.rpm
warning: dracut-kiwi-lib-9.23.40-1.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 7bf939ef: NOKEY
/bin/bash
bc
btrfsprogs
coreutils
cryptsetup
curl
device-mapper
dialog
e2fsprogs
gptfdisk
grep
lvm2
mdadm
parted
pv
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
util-linux
xfsprogs
xz
```

**Comment by dcermak** [comment]
Marcus Schäfer ***@***.***> writes:

> ```
> # lsblk is part of util-linux-systemd on openSUSE
> %if 0%{?suse_version}
> Requires:       util-linux-systemd
> %endif
> ```
>
> is this working for TW ?

It should. But this line is nowhere in the spec file in
Virtualization:Appliances:Builder/python-kiwi

**Comment by dcermak** [comment]
> This seemed to have no effect
> 
> ```
> rpm -qp --requires dracut-kiwi-lib-9.23.40-1.1.x86_64.rpm
> warning: dracut-kiwi-lib-9.23.40-1.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 7bf939ef: NOKEY
> /bin/bash
> bc
> btrfsprogs
> coreutils
> cryptsetup
> curl
> device-mapper
> dialog
> e2fsprogs
> gptfdisk
> grep
> lvm2
> mdadm
> parted
> pv
> rpmlib(CompressedFileNames) <= 3.0.4-1
> rpmlib(FileDigests) <= 4.6.0-1
> rpmlib(PayloadFilesHavePrefix) <= 4.0-1
> rpmlib(PayloadIsZstd) <= 5.4.18-1
> util-linux
> xfsprogs
> xz
> ```

Ah, apologies, I've looked into the wrong project.

And there is a very simple explanation why you are not seing `util-linux-systemd` in there: I only added it as a dependency to `dracut-kiwi-overlay`… I'll fix this in a minute.

**Comment by schaefi** [comment]
@dcermak with the latest kiwi package update in Staging the image builds in question worked again

From my perspective there is then only one left which is:

* the created microos disk image still tries to install twice, but I have not looked into that yet so this might be an openQA/my test setup issue

That part I still can't reproduce or did not understand :)

**Comment by dcermak** [comment]
I have done a full openQA of Fedora & openSUSE today with the latest images and after a bit of restarting and additional tweaking, the only failure that remains is this weird MicroOS failure. I have honestly no idea really what is going wrong there and will have to debug this a bit more.

Now the next step is to get this all running on o3.

**Comment by dcermak** [comment]
The mystery around the mircoOS image is solved as well: for some reason openQA will boot once again from the iso when using a UEFI firmware and not prefer the HDD. But since the bootloader remains invisible in UEFI mode, we cannot let openQA select the correct entry in grub. I've dug around in openQA's documentation and found `eject_cd` which does the trick here.

I'll perform a full validation run this night and if that succeeds, then I'd close this issue and take a look at moving the test suite to o3.

**Comment by dcermak** [comment]
Ok, bummer. It turns out that a whole bunch of disk images that are created from installation isos are broken. This appeared now after I've included `eject_cd` call, so it turns out that openqa was actually booting from the isos in a bunch of tests :disappointed:

**Comment by dcermak** [comment]
And back to good news: it turns out that I had a few additional brain farts in my test setup and now the only failing image is the disk image produced by the test-image-ramdisk isos:
- https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/tumbleweed/images/iso/kiwi-test-image-disk-ramdisk.x86_64-1.42.1-Build9.26.install.iso
- https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/Testing_x86:/leap/images/iso/kiwi-test-image-disk-ramdisk.x86_64-1.15.3-Build9.7.install.iso

openQA successfully creates a disk image when booting from that iso, but it cannot boot from the resulting disk image.

I can also reproduce this issue locally with virt-manager: I create a new VM, insert the ISO, let it run the installation and then trying to boot from the resulting qcow2 image fails.

**Comment by dcermak** [comment]
Well, my last comment was a brainfart, as the ramdisk iso does not actually write anything to disk… So the images appear to all be working.
